apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: helmsecretpruner
  name: helmsecretpruner:allow-secret-delete
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helmsecretpruner-cluster-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: helmsecretpruner
  name: helmsecretpruner:allow-namespace-list
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: allow-namespace-list
subjects:
- kind: ServiceAccount
  name: default
  namespace: ${NAMESPACE}