apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: helmsecretpruner-cluster-role
  name: helmsecretpruner-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - delete
      - list